apiVersion: v1
kind: Service
metadata:
  name: voyage-analytics-service
  labels:
    app: voyage-analytics
spec:
  selector:
    app: voyage-analytics
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
